import { RelatedProduct } from "../types/relatedProduct";
import { CardData } from "../types/cardData";
import { Insight, InteractiveText } from "../types/insight";
import { sampleDataDescription } from "./data_description";

export const imageBaseUrl =
  "https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com";

export const sampleRelatedProduct: RelatedProduct[] = [
  {
    type: "API",
    name: "수도권 지하철 열차혼잡도",
    partner: "서울교통공사",
  },
];

export const newSampleInsightList: { [key: string]: any[] } = {
  "지하철-혼잡도": [
    {
      id: "101",
      imgSrc: `/images/puzzle_card_subway1.png`,
      title: "지하철 칸 혼잡도",
      category: "체험형 인사이트",
      isNew: true,
      description: "지하철 칸 혼잡도를 확인할 수 있습니다",
      tagList: ["지하철", "대중교통", "혼잡도", "코로나"],
      cardType: "normal",
      dataType: "insights",
      type: "interactive",
      interactiveType: "subwayCongestionCar",
      reportContent: null,
      displayName: "지하철-칸-혼잡도",
    },
    {
      id: "102",
      imgSrc: `/images/puzzle_card_subway2.png`,
      title: "지하철 경로 혼잡도",
      category: "체험형 인사이트",
      isNew: true,
      description:
        "검색한 역사 기준으로 사람들이 많이 이용하는 경로의 혼잡도를 제공합니다",
      tagList: ["지하철", "대중교통", "혼잡도", "코로나"],
      cardType: "normal",
      dataType: "insights",
      type: "interactive",
      interactiveType: "subwayCongestionRoute",
      reportContent: null,
      displayName: "지하철-경로-혼잡도",
    },
    {
      id: "103",
      imgSrc: `/images/puzzle_card_subway3.png`,
      title: "지하철 열차 혼잡도",
      category: "체험형 인사이트",
      isNew: true,
      description:
        "검색한 역으로 진입하는 지하철의 혼잡도를 시간대별로 확인할 수 있습니다",
      tagList: ["지하철", "대중교통", "혼잡도", "코로나"],
      cardType: "normal",
      dataType: "insights",
      type: "interactive",
      interactiveType: "subwayCongestionTrain",
      reportContent: null,
      displayName: "지하철-열차-혼잡도",
    },
    {
      id: "1",
      category: "인사이트",
      isNew: true,
      cardType: "normal",
      dataType: "insights",
      type: "report",
      imgSrc: `/images/puzzle_card_subway4.png`,
      title: "호선별 출퇴근길 가장 혼잡한 구간",
      displayName: "호선별 출퇴근길 가장 혼잡한 구간",
      partner: "서울교통공사, TMAP MOBILITY",
      tagList: ["혼잡도", "지하철"],
      description:
        "수도권 1~9호선 및 신분당선의 출퇴근길 가장 혼잡한 구간을 확인할 수 있습니다.",
      reportContent:
        "\n수도권 1~9호선 및 신분당선의 출/퇴근길 가장 혼잡한 구간을 확인할 수 있습니다.\n\n![Image](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/3672d904-91a2-45d3-9e5f-a32e9341e269_fig.svg)\n\n",
    },
    {
      id: "2",
      category: "인사이트",
      isNew: true,
      cardType: "normal",
      dataType: "insights",
      type: "report",
      imgSrc: `/images/puzzle_card_subway5.png`,
      title: "수도권 지하철의 연령대별 이용 순위",
      displayName: "수도권 지하철의 연령대별 이용 순위",
      partner: "서울교통공사, TMAP MOBILITY",
      tagList: ["혼잡도", "지하철"],
      description: "수도권 지하철역의 연령대별 이용 순위를 확인할 수 있습니다.",
      reportContent:
        "\n수도권 지하철역의 연령대별 이용 순위를 확인할 수 있습니다.\n\n10 ~ 20대는 홍대입구역, 강남역 등 번화가 근처의 이용 순위가 높은 반면,  \n30 ~ 50대는 강남역, 가산디지털단지역, 선릉역, 여의도역 등 회사 밀집 지역의 순위가 높게 나타났습니다. \n\n![Image](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/906f26c2-dd2c-4266-97e4-f8df0a177202_fig.svg)\n\n",
    },
    {
      id: "3",
      category: "인사이트",
      isNew: true,
      cardType: "normal",
      dataType: "insights",
      type: "report",
      imgSrc: `/images/puzzle_card_subway6.png`,
      title: "퇴근 시간의 신도림역~강남역 경로 혼잡도",
      displayName: "퇴근 시간의 신도림역~강남역 경로 혼잡도",
      partner: "서울교통공사, TMAP MOBILITY",
      tagList: ["혼잡도", "지하철"],
      description:
        "퇴근 시간에 신도림역에서 강남역으로 가려고 할 때, 몇 시에 지하철을 타야 비교적 한산하게 갈 수 있을까요?",
      reportContent:
        "\n퇴근 시간에 신도림역에서 강남역으로 가려고 할 때, 몇 시에 지하철을 타야 비교적 한산하게 갈 수 있을까요?\n\n17시 30분 이전에 신도림역에서 승차한다면 신대방역까지는 비교적 한산하게 갈 수 있지만 신림역부터 점차 혼잡해지며,   \n19시 이후에 신도림역에서 출발하면 강남역까지 가장 한산하게 갈 수 있습니다.   \n가장 혼잡한 승차 시간은 18시 20분 ~ 40분으로, 이 시간에 신도림역에서 강남역으로 가려고 한다면 매우 혼잡한 열차를 탑승하게 됩니다.\n\n![Image](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/f5c9fa37-d404-42a8-8c03-b15efc295d1a_fig.svg)\n\n",
    },
    {
      id: "4",
      category: "인사이트",
      isNew: true,
      cardType: "normal",
      dataType: "insights",
      type: "report",
      imgSrc: `/images/puzzle_card_subway7.png`,
      title: "하차 역사별 탑승칸의 비율",
      displayName: "하차 역사별 탑승칸의 비율",
      partner: "서울교통공사, TMAP MOBILITY",
      tagList: ["혼잡도", "지하철"],
      description: "하차하는 역에 따라 사람들이 선호하는 탑승 칸은 달라집니다.",
      reportContent:
        "\n하차하는 역에 따라 사람들이 선호하는 탑승 칸은 달라집니다.  \n\n특히 출구와 가까운 칸이 존재하는 경우, 특정 칸의 선호 비율이 두드러집니다.  \n예를 들어, 6호선 독바위역의 빠른 하차 칸은 3-2번이며, 독바위역에서 하차하는 승객의 41%는 3번칸에 탑승합니다.\n\n![Image](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/341a9459-4b54-486e-9d02-5f8ec632af3a_fig.svg)\n\n",
    },
    {
      id: "5",
      category: "인사이트",
      isNew: true,
      cardType: "normal",
      dataType: "insights",
      type: "report",
      imgSrc: `/images/puzzle_card_subway8.png`,
      title: "일별 지하철 이용 건수",
      displayName: "일별 지하철 이용 건수",
      partner: "서울교통공사, TMAP MOBILITY",
      tagList: ["혼잡도", "지하철"],
      description: "수도권 1~9호선의 일자별 이용 건수를 확인할 수 있습니다.",
      reportContent:
        "\n수도권 1~9호선의 일자별 이용 건수를 확인할 수 있습니다.  \n\n일반적으로 평일에 비해 주말의 이용 건수는 절반 정도로 감소하며, 2022년 1월과 2월에는 이용 건수가 점차 감소하는 추세를 보입니다.\n\n![Image](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/be107bed-ba24-46c5-92c1-9a2147ef2fda_fig.svg)\n\n",
    },
    {
      id: "6",
      category: "인사이트",
      isNew: true,
      cardType: "normal",
      dataType: "insights",
      type: "report",
      imgSrc: `/images/puzzle_card_subway9.png`,
      title: "연령대별 탑승 시간대별 이용 건수",
      displayName: "연령대별 탑승 시간대별 이용 건수",
      partner: "서울교통공사, TMAP MOBILITY",
      tagList: ["혼잡도", "지하철"],
      description:
        "수도권 지하철의 연령대별 탑승 시간대별 이용 건수를 확인할 수 있습니다.",
      reportContent:
        "\n수도권 지하철의 연령대별 탑승 시간대별 이용 건수를 확인할 수 있습니다. \n\n오전 5시와 낮 시간대(10시~16시)에는 60대 이상의 이용 건수가 가장 높은 반면,  \n출퇴근 시간대에는 30대, 20대, 40대 순으로 높은 이용 건수를 보입니다.  \n20시 이후부터는 20대의 이용 건수가 가장 높으며, 가게 영업이 종료하는 21시까지 이용 건수가 증가하다가 점차 감소합니다.  \n\n![Image](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/6be14b4b-93dd-45de-bd76-7cc8f35ed017_fig.svg)\n\n",
    },
    {
      id: "7",
      category: "인사이트",
      isNew: true,
      cardType: "normal",
      dataType: "insights",
      type: "report",
      imgSrc: `/images/puzzle_card_subway10.png`,
      title: "출근시간대 판교역으로 이동성",
      displayName: "출근시간대 판교역으로 이동성",
      partner: "서울교통공사, TMAP MOBILITY",
      tagList: ["혼잡도", "지하철"],
      description:
        "오전 07시 ~ 오전 10시 까지 출근시간동안 판교역에 도착한 사람들이 어떤 역사에서 출발했는지 시각화한 자료입니다.",
      reportContent:
        "\n\n오전 07시 ~ 오전 10시 까지 출근시간동안 판교역에 도착한 사람들이 어떤 역사에서 출발했는지 시각화한 자료입니다.  \n비율은 각 역사별로 출발한 사람 수를 판교역에 해당 시각에 도착한 사람들의 전체 수로 나눠준 값입니다.\n\n\n![900, 605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/7e4c3b2b-6481-4509-85ff-19b2f6b47b7d_fig.svg)\n\n\n",
    },
    {
      id: "8",
      category: "인사이트",
      isNew: true,
      cardType: "normal",
      dataType: "insights",
      type: "report",
      imgSrc: `/images/puzzle_card_subway11.png`,
      title: "출근시간대 강남권으로 이동성",
      displayName: "출근시간대 강남권으로 이동성",
      partner: "서울교통공사, TMAP MOBILITY",
      tagList: ["혼잡도", "지하철"],
      description:
        "오전 07시 ~ 오전 10시 까지 강남, 신논현, 역삼에 도착한 사람들이 어떤 역사에서 출발했는지 볼 수 있습니다.",
      reportContent:
        "\n\n오전 07시 ~ 오전 10시 까지 강남, 신논현, 역삼에 도착한 사람들이 어떤 역사에서 출발했는지 볼 수 있습니다.  \n비율은 각 역사별로 출발한 사람 수를 강남권에 해당 시각에 도착한 사람들의 전체 수로 나눠준 값입니다.\n\n\n![900, 605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/a395bb92-826f-4c16-a736-e8ed3b0c39bc_fig.svg)\n\n\n",
    },
    {
      id: "9",
      category: "인사이트",
      isNew: true,
      cardType: "normal",
      dataType: "insights",
      type: "report",
      imgSrc: `/images/puzzle_card_subway12.png`,
      title: "출근시간대 분당에서 이동성",
      displayName: "출근시간대 분당에서 이동성",
      partner: "서울교통공사, TMAP MOBILITY",
      tagList: ["혼잡도", "지하철"],
      description:
        "오전 06시 ~ 오전 9시 까지 오리역, 미금역, 정자역, 수내역, 서현역, 이매역에서 지하철을 탑승한 사람들이 어떤 역사에 많이 하차하는지 볼 수 있습니다.",
      reportContent:
        "\n\n오전 06시 ~ 오전 9시 까지 오리역, 미금역, 정자역, 수내역, 서현역, 이매역에서 지하철을 탑승한 사람들이 어떤 역사에 많이 하차하는지 볼 수 있습니다.  \n비율은 각 역사별로 도착한 사람 수를 분당권에서 해당 시각에 출발한 사람들의 전체 수로 나눠준 값입니다.\n\n\n![900, 605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/8f3540a2-46f1-4b69-8f89-fb0a417cc9a4_fig.svg)\n\n\n",
    },
    {
      id: "10",
      category: "인사이트",
      isNew: true,
      cardType: "normal",
      dataType: "insights",
      type: "report",
      imgSrc: `/images/puzzle_card_subway13.png`,
      title: "출근시간대 평촌에서 이동성",
      displayName: "출근시간대 평촌에서 이동성",
      partner: "서울교통공사, TMAP MOBILITY",
      tagList: ["혼잡도", "지하철"],
      description:
        "오전 06시 ~ 오전 9시 까지 범계역, 평촌역에서 지하철을 탑승한 사람들이 어떤 역사에 많이 하차하는지 볼 수 있습니다.",
      reportContent:
        "\n\n오전 06시 ~ 오전 9시 까지 범계역, 평촌역에서 지하철을 탑승한 사람들이 어떤 역사에 많이 하차하는지 볼 수 있습니다.  \n비율은 각 역사별로 도착한 사람 수를 평촌권에서 해당 시각에 출발한 사람들의 전체 수로 나눠준 값입니다.\n\n\n![900, 605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/a6f352c7-6a1d-4e93-b14f-1b66d5d976c1_fig.svg)\n\n\n",
    },
    {
      id: "11",
      category: "인사이트",
      isNew: true,
      cardType: "normal",
      dataType: "insights",
      type: "report",
      imgSrc: `/images/puzzle_card_subway14.png`,
      title: "출근시간대 일산에서 이동성",
      displayName: "출근시간대 일산에서 이동성",
      partner: "서울교통공사, TMAP MOBILITY",
      tagList: ["혼잡도", "지하철"],
      description:
        "오전 06시 ~ 오전 9시 까지 대화역, 주엽역, 정발산역, 마두역, 백석역에서 지하철을 탑승한 사람들이 어떤 역사에 많이 하차하는지 볼 수 있습니다.",
      reportContent:
        "\n\n오전 06시 ~ 오전 9시 까지 대화역, 주엽역, 정발산역, 마두역, 백석역에서 지하철을 탑승한 사람들이 어떤 역사에 많이 하차하는지 볼 수 있습니다.  \n비율은 각 역사별로 도착한 사람 수를 일산권에서 해당 시각에 출발한 사람들의 전체 수로 나눠준 값입니다.\n\n\n![900, 605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/4deb8c07-4c73-4904-af19-cb6be1bc2e8a_fig.svg)\n\n\n",
    },
  ],
  "쇼핑,여가-장소-혼잡도": [
    {
      id: "1",
      imgSrc: `/images/puzzle_card_poi1.png`,
      title: "쇼핑/여가 장소 혼잡도",
      category: "체험형 인사이트",
      isNew: false,
      description: "쇼핑몰의 혼잡도를 알아보세요",
      tagList: ["이동", "혼잡도", "쇼핑"],
      cardType: "normal",
      dataType: "insights",
      type: "interactive",
      interactiveType: "poiCongestionHourly",
      reportContent: null,
      displayName: "쇼핑,여가-장소-혼잡도",
    },
    {
      id: "12",
      category: "인사이트",
      isNew: true,
      cardType: "normal",
      dataType: "insights",
      type: "report",
      imgSrc: `/images/puzzle_card_poi2.png`,
      title: "스타필드의 지점별 가장 혼잡한 시간대",
      displayName: "스타필드의 지점별 가장 혼잡한 시간대",
      partner: "SKTelecom",
      tagList: ["여가", "쇼핑", "장소"],
      description:
        "쇼핑몰별로 가장 혼잡한 시간대를 확인할 수 있습니다. 1개월 간 요일/시간대별 평균 혼잡도 중 가장 혼잡한 시간대를 기준(100)으로 통계성 혼잡도를 제공합니다. 스타필드시티부천과 스타필드하남의 요일/시간대별 혼잡도를 확인해보세요. 평균적으로 스타필드시티부천은 토요일 16시에 가장 혼잡합니다. 스타필드 하남은 일요일 15시에 혼잡합니다",
      reportContent:
        "\n쇼핑몰별로 가장 혼잡한 시간대를 확인할 수 있습니다. 1개월 간 요일/시간대별 평균 혼잡도 중 가장 혼잡한 시간대를 기준(100)으로 통계성 혼잡도를 제공합니다.  스타필드시티부천과 스타필드하남의 요일/시간대별 혼잡도를 확인해보세요.\n\n평균적으로 스타필드시티부천은 토요일 16시에 가장 혼잡합니다.\n![Image](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/23ffff9b-c08c-48a0-93e5-42555e3753a5_%EC%8A%A4%ED%83%80%ED%95%84%EB%93%9C%ED%95%98%EB%82%A8%285411247%29%20%ED%86%B5%EA%B3%84%EC%84%B1%20%ED%98%BC%EC%9E%A1%EB%8F%84.svg)\n\n스타필드 하남은 일요일 15시에 혼잡합니다. \n![Image](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/a9a9aab5-40ed-48ae-8715-045c22b98ec9_%EC%8A%A4%ED%83%80%ED%95%84%EB%93%9C%EC%8B%9C%ED%8B%B0%EB%B6%80%EC%B2%9C%287979646%29%20%ED%86%B5%EA%B3%84%EC%84%B1%20%ED%98%BC%EC%9E%A1%EB%8F%84.svg)\n",
    },
    {
      id: "13",
      category: "인사이트",
      isNew: true,
      cardType: "normal",
      dataType: "insights",
      type: "report",
      imgSrc: `/images/puzzle_card_poi3.png`,
      title: "새벽시간에 혼잡한 쇼핑몰",
      displayName: "새벽시간에 혼잡한 쇼핑몰",
      partner: "SKTelecom",
      tagList: ["여가", "쇼핑", "장소"],
      description:
        "신세계백화점강남점은 토요일, 일요일에 평일보다 2배 정도 더 혼잡합니다. 동대문에 있는 누죤은 다른 쇼핑몰과는 달리 월요일 23시에 가장 혼잡합니다. 토요일~일요일을 뺀 평일 새벽시간대(21시 ~ 새벽4시)에 혼잡한 것을 확인할 수 있습니다",
      reportContent:
        "\n신세계백화점강남점은 토요일, 일요일에 평일보다 2배 정도 더 혼잡합니다. \n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/1d53d04c-cdb4-4250-95d2-c8275b05deb5_%EC%8B%A0%EC%84%B8%EA%B3%84%EB%B0%B1%ED%99%94%EC%A0%90%EA%B0%95%EB%82%A8%EC%A0%90%28214920%29%20%ED%86%B5%EA%B3%84%EC%84%B1%20%ED%98%BC%EC%9E%A1%EB%8F%84.svg)\n\n동대문에 있는 누죤은 다른 쇼핑몰과는 달리 월요일 23시에 가장 혼잡합니다. 토요일~일요일을 뺀 평일 새벽시간대(21시 ~ 새벽4시)에 혼잡한 것을 확인할 수 있습니다.\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/4db2d675-18a8-4d5c-bae4-997fab621c3f_%EB%88%84%EC%A3%A4%28219021%29%20%ED%86%B5%EA%B3%84%EC%84%B1%20%ED%98%BC%EC%9E%A1%EB%8F%84.svg)\n",
    },
    {
      id: "14",
      category: "인사이트",
      isNew: true,
      cardType: "normal",
      dataType: "insights",
      type: "report",
      imgSrc: `/images/puzzle_card_poi4.png`,
      title: "혼잡도가 증가하고 있는 더현대서울",
      displayName: "혼잡도가 증가하고 있는 더현대서울",
      partner: "SKTelecom",
      tagList: ["여가", "쇼핑", "장소"],
      description:
        "2월 중순부터 더현대서울의 일자별 혼잡도가 증가합니다. 1월 이후부터 더현대서울의 방문자수가 증가하고 있는 것을 확인해보세요. 휴무일이었던 3월 1일(화), 3월 9일(수)에도 평소 주말만큼 혼잡한 것을 알 수 있습니다",
      reportContent:
        "\n2월 중순부터 더현대서울의 일자별 혼잡도가 증가합니다. 1월 이후부터 더현대서울의 방문자수가 증가하고 있는 것을 확인해보세요. 휴무일이었던 3월 1일(화), 3월 9일(수)에도 평소 주말만큼 혼잡한 것을 알 수 있습니다.\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/88a84fbd-369b-4699-bb66-8586e8dda0be_%EB%8D%94%ED%98%84%EB%8C%80%EC%84%9C%EC%9A%B8%2810067845%29%20Daily%20%ED%98%BC%EC%9E%A1%EB%8F%84.svg)\n",
    },
    {
      id: "15",
      category: "인사이트",
      isNew: true,
      cardType: "normal",
      dataType: "insights",
      type: "report",
      imgSrc: `/images/puzzle_card_poi5.png`,
      title: "설연휴 직전 혼잡도 급증한 하나로마트",
      displayName: "설연휴 직전 혼잡도 급증한 하나로마트",
      partner: "SKTelecom",
      tagList: ["여가", "쇼핑", "장소"],
      description:
        "하나로마트는 설연휴 직전까지 1월의 혼잡도가 급증하는 모습을 보입니다. 설연휴 이후에는 1월에 비해 혼잡도가 감소하는 모습을 보입니다. 하나로마트수원점과 하나로마트청주점의 일자별혼잡도가 비슷한 것을 확인할 수 있습니다",
      reportContent:
        "\n하나로마트는 설연휴 직전까지 1월의 혼잡도가 급증하는 모습을 보입니다. 설연휴 이후에는 1월에 비해 혼잡도가 감소하는 모습을 보입니다. 하나로마트수원점과 하나로마트청주점의 일자별혼잡도가 비슷한 것을 확인할 수 있습니다. \n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/17709fd4-3c76-4b04-934a-1973a85132ea_%ED%95%98%EB%82%98%EB%A1%9C%EB%A7%88%ED%8A%B8%EC%88%98%EC%9B%90%EC%A0%90%284091106%29%20Daily%20%ED%98%BC%EC%9E%A1%EB%8F%84.svg)\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/e23df6fe-8c8e-4cc9-bfc5-5e32023ab9b9_%ED%95%98%EB%82%98%EB%A1%9C%EB%A7%88%ED%8A%B8%EC%B2%AD%EC%A3%BC%EC%A0%90%28557159%29%20Daily%20%ED%98%BC%EC%9E%A1%EB%8F%84.svg)\n",
    },
    {
      id: "16",
      category: "인사이트",
      isNew: true,
      cardType: "normal",
      dataType: "insights",
      type: "report",
      imgSrc: `/images/puzzle_card_poi6.png`,
      title: "설연휴 직전 혼잡도 급증한 롯데마트",
      displayName: "설연휴 직전 혼잡도 급증한 롯데마트",
      partner: "SKTelecom",
      tagList: ["여가", "쇼핑", "장소"],
      description:
        "롯데마트는 설연휴 직전에 가장 혼잡한 모습을 보입니다. 혼잡도가 거의 없는 구간은 휴무일을 의미합니다. 롯데마트서울역점과 롯데마트송파점의 일자별혼잡도 트렌드가 비슷한 것을 확인할 수 있습니다. 롯데마트서울역점은 설연휴 직전에 가장 혼잡하다가, 설연휴 이후에 혼잡도가 약간 감소하는 모습을 보입니다. 롯데마트송파점의 경우 2월 이후에 1월에 비해 혼잡도가 감소한 것을 확인할 수 있습니다",
      reportContent:
        "\n롯데마트는 설연휴 직전에 가장 혼잡한 모습을 보입니다. 혼잡도가 거의 없는 구간은 휴무일을 의미합니다. 롯데마트서울역점과 롯데마트송파점의 일자별혼잡도 트렌드가 비슷한 것을 확인할 수 있습니다. \n\n롯데마트서울역점은 설연휴 직전에 가장 혼잡하다가, 설연휴 이후에 혼잡도가 약간 감소하는 모습을 보입니다.\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/f25da2e2-93a8-467f-9180-b73c28d406b6_%EB%A1%AF%EB%8D%B0%EB%A7%88%ED%8A%B8%EC%84%9C%EC%9A%B8%EC%97%AD%EC%A0%90%281103492%29%20Daily%20%ED%98%BC%EC%9E%A1%EB%8F%84.svg)\n\n롯데마트송파점의 경우 2월 이후에 1월에 비해 혼잡도가 감소한 것을 확인할 수 있습니다.\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/5fadf3f7-9fae-4029-9ea9-a40048fd96c8_%EB%A1%AF%EB%8D%B0%EB%A7%88%ED%8A%B8%EC%86%A1%ED%8C%8C%EC%A0%90%28188492%29%20Daily%20%ED%98%BC%EC%9E%A1%EB%8F%84.svg)\n",
    },
    {
      id: "17",
      category: "인사이트",
      isNew: true,
      cardType: "normal",
      dataType: "insights",
      type: "report",
      imgSrc: `/images/puzzle_card_poi7.png`,
      title: "설연휴 직전 혼잡도 급증한 이마트",
      displayName: "설연휴 직전 혼잡도 급증한 이마트",
      partner: "SKTelecom",
      tagList: ["여가", "쇼핑", "장소"],
      description:
        "이마트는 설연휴 직전에만 혼잡도가 급증하는 모습을 보입니다. 설연휴 이후에는 1월의 평소 혼잡도를 보이는 것을 알 수 있습니다. 이마트파주운정점과 이마트화정점의 일자별혼잡도가 비슷한 것을 확인해보세요",
      reportContent:
        "\n이마트는 설연휴 직전에만 혼잡도가 급증하는 모습을 보입니다. 설연휴 이후에는 1월의 평소 혼잡도를 보이는 것을 알 수 있습니다. 이마트파주운정점과 이마트화정점의 일자별혼잡도가 비슷한 것을 확인해보세요.\n\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/88336bf1-e1b4-4c53-a58f-22d7a4efc3b9_%EC%9D%B4%EB%A7%88%ED%8A%B8%ED%8C%8C%EC%A3%BC%EC%9A%B4%EC%A0%95%EC%A0%90%282751805%29%20Daily%20%ED%98%BC%EC%9E%A1%EB%8F%84.svg)\n\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/6a0fa70b-0a4f-48e4-bd49-e83687d840bf_%EC%9D%B4%EB%A7%88%ED%8A%B8%ED%99%94%EC%A0%95%EC%A0%90%28504531%29%20Daily%20%ED%98%BC%EC%9E%A1%EB%8F%84.svg)\n",
    },
    {
      id: "18",
      category: "인사이트",
      isNew: true,
      cardType: "normal",
      dataType: "insights",
      type: "report",
      imgSrc: `/images/puzzle_card_poi8.png`,
      title: "1월 이후 방문자수가 감소하는 백화점",
      displayName: "1월 이후 방문자수가 감소하는 백화점",
      partner: "SKTelecom",
      tagList: ["여가", "쇼핑", "장소"],
      description:
        "전국의 대부분의 백화점이 1월 이후부터 방문자수가 감소하고 있습니다. 롯데백화점, 현대백화점, 신세계백화점, 갤러이아백화점의 일자별혼잡도를 통해 감소하고 있는 혼잡도를 확인해보세요",
      reportContent:
        "\n전국의 대부분의 백화점이 1월 이후부터 방문자수가 감소하고 있습니다. 롯데백화점, 현대백화점, 신세계백화점, 갤러이아백화점의 일자별혼잡도를 통해 감소하고 있는 혼잡도를 확인해보세요\n\n#### [1] 롯데백화점\n\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/49b47842-4e5e-4deb-b3ba-a3aa772926b9_%EB%A1%AF%EB%8D%B0%EB%B0%B1%ED%99%94%EC%A0%90%EB%B3%B8%EC%A0%90%28219475%29%20Daily%20%ED%98%BC%EC%9E%A1%EB%8F%84.svg)\n\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/7fcd8793-5289-4dc9-8ca5-6466f4fd76f6_%EB%A1%AF%EB%8D%B0%EB%B0%B1%ED%99%94%EC%A0%90%EC%98%81%EB%93%B1%ED%8F%AC%EC%A0%90%28189138%29%20Daily%20%ED%98%BC%EC%9E%A1%EB%8F%84.svg)\n\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/9e84e660-3c88-47cb-bc78-08b3fedd3b6a_%EB%A1%AF%EB%8D%B0%EB%B0%B1%ED%99%94%EC%A0%90%EC%97%90%EB%B9%84%EB%89%B4%EC%97%98%EC%9B%94%EB%93%9C%ED%83%80%EC%9B%8C%EC%A0%90%285783805%29%20Daily%20%ED%98%BC%EC%9E%A1%EB%8F%84.svg)\n\n#### [2] 현대백화점\n\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/4df525cf-01d2-46e5-99d3-1952ebbc3b2e_%ED%98%84%EB%8C%80%EB%B0%B1%ED%99%94%EC%A0%90%EB%AA%A9%EB%8F%99%EC%A0%90%28551216%29%20Daily%20%ED%98%BC%EC%9E%A1%EB%8F%84.svg)\n\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/4199a010-ff36-4c01-baae-9e4d0a2e5e79_%ED%98%84%EB%8C%80%EB%B0%B1%ED%99%94%EC%A0%90%EC%8B%A0%EC%B4%8C%EC%A0%90%28366844%29%20Daily%20%ED%98%BC%EC%9E%A1%EB%8F%84.svg)\n\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/8ac1ccb9-3fb6-4f64-ba0a-cb4dc4518c95_%ED%98%84%EB%8C%80%EB%B0%B1%ED%99%94%EC%A0%90%EC%A4%91%EB%8F%99%EC%A0%90%28540476%29%20Daily%20%ED%98%BC%EC%9E%A1%EB%8F%84.svg)\n\n#### [3] 신세계백화점\n\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/a9fde4d3-3bba-4610-8a86-dc0d59a32047_%EC%8B%A0%EC%84%B8%EA%B3%84%EB%B0%B1%ED%99%94%EC%A0%90%EB%B3%B8%EC%A0%90%281436708%29%20Daily%20%ED%98%BC%EC%9E%A1%EB%8F%84.svg)\n\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/910439e6-084e-474a-ad92-df7c2d0240fc_%EC%8B%A0%EC%84%B8%EA%B3%84%EB%B0%B1%ED%99%94%EC%A0%90%EA%B2%BD%EA%B8%B0%EC%A0%90%281198235%29%20Daily%20%ED%98%BC%EC%9E%A1%EB%8F%84.svg)\n\n",
    },
    {
      id: "19",
      category: "인사이트",
      isNew: true,
      cardType: "normal",
      dataType: "insights",
      type: "report",
      imgSrc: `/images/puzzle_card_poi9.png`,
      title: "방문자수가 증가하는 아울렛",
      displayName: "방문자수가 증가하는 아울렛",
      partner: "SKTelecom",
      tagList: ["여가", "쇼핑", "장소"],
      description:
        "전국의 백화점이 1월 이후에 방문자수가 감소하는 반면, 아울렛은 혼잡도가 증가한 것을 확인할 수 있습니다. 아울렛은 특히 삼일절 직전 주말에 가장 혼잡한 모습을 보였고, 삼일절과 대통령선거일에도 주말의 혼잡도가 유지되는 것을 확인할 수 있습니다",
      reportContent:
        "\n전국의 백화점이 1월 이후에 방문자수가 감소하는 반면, 아울렛은 혼잡도가 증가한 것을 확인할 수 있습니다. 아울렛은 특히 삼일절 직전 주말에 가장 혼잡한 모습을 보였고, 삼일절과 대통령선거일에도 주말의 혼잡도가 유지되는 것을 확인할 수 있습니다. \n\n#### [1] 신세계프리미엄아울렛\n\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/1b0c6db6-affb-48f4-8b2c-1cf98c13a202_%EC%8B%A0%EC%84%B8%EA%B3%84%ED%94%84%EB%A6%AC%EB%AF%B8%EC%97%84%EC%95%84%EC%9A%B8%EB%A0%9B%EC%8B%9C%ED%9D%A5%EC%A0%90%286523495%29%20Daily%20%ED%98%BC%EC%9E%A1%EB%8F%84.svg)\n\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/7ac27d84-8c77-4abe-96aa-4465cd40eca1_%EC%8B%A0%EC%84%B8%EA%B3%84%ED%94%84%EB%A6%AC%EB%AF%B8%EC%97%84%EC%95%84%EC%9A%B8%EB%A0%9B%EC%97%AC%EC%A3%BC%EC%A0%90%28WEST%29%286804439%29%20Daily%20%ED%98%BC%EC%9E%A1%EB%8F%84.svg)\n\n#### [2] 롯데프리미엄아울렛\n\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/387aa563-0982-48ef-8335-f49cfc902550_%EB%A1%AF%EB%8D%B0%ED%94%84%EB%A6%AC%EB%AF%B8%EC%97%84%EC%95%84%EC%9A%B8%EB%A0%9B%EC%9D%B4%EC%B2%9C%EC%A0%90%282964028%29%20Daily%20%ED%98%BC%EC%9E%A1%EB%8F%84.svg)\n\n#### [3] 현대프리미엄아울렛\n\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/896d32ae-af1c-4995-a527-0a84005bd25a_%ED%98%84%EB%8C%80%ED%94%84%EB%A6%AC%EB%AF%B8%EC%97%84%EC%95%84%EC%9A%B8%EB%A0%9B%EC%86%A1%EB%8F%84%EC%A0%90%286809386%29%20Daily%20%ED%98%BC%EC%9E%A1%EB%8F%84.svg)\n\n",
    },
    {
      id: "20",
      category: "인사이트",
      isNew: true,
      cardType: "normal",
      dataType: "insights",
      type: "report",
      imgSrc: `/images/puzzle_card_poi1.png`,
      title: "연령대별로 방문하는 백화점이 다른 부산",
      displayName: "연령대별로 방문하는 백화점이 다른 부산",
      partner: "SKTelecom",
      tagList: ["여가", "쇼핑", "장소"],
      description:
        "2022년 2월 기준 방문자들의 연령대/성별 분포를 통해 장소별 방문자의 특징을 확인해보세요. 그래프의 색깔은 스타필드하남에 방문한 해당 연령대/성별의 비율이 원래 그 연령대/성별의 비율보다 높다는 것을 의미합니다. 현대백화점부산점은 50대, 60대이상 여성의 비율이 다른 쇼핑몰의 평균에 비해 매우 높은 것을 볼 수 있습니다 . 롯데백화점부산본점은 현대백화점부산점에 비해 방문자의 연령대분포가 낮아진 것을 확인할 수 있습니다. 4, 50대 여성의 비율이 다른 쇼핑몰 방문자 평균에 비해 높은 것을 확인할 수 있습니다. 신세계백화점센텀시티점은 현대백화점, 롯데백화점보다 방문자의 연령이 어린 것을 확인할 수 있습니다. 특히 2~40대 여성의 비율이 높게 나타납니다",
      reportContent:
        "\n2022년 2월 기준 방문자들의 연령대/성별 분포를 통해 장소별 방문자의 특징을 확인해보세요. 그래프의 색깔은 스타필드하남에 방문한 해당 연령대/성별의 비율이 원래 그 연령대/성별의 비율보다 높다는 것을 의미합니다.\n\n현대백화점부산점은 50대, 60대이상 여성의 비율이 다른 쇼핑몰의 평균에 비해 매우 높은 것을 볼 수 있습니다.\n\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/8c5478cf-1ffb-4c10-ba3b-507260835e50_%ED%98%84%EB%8C%80%EB%B0%B1%ED%99%94%EC%A0%90%EB%B6%80%EC%82%B0%EC%A0%90%28151893%29%20%EC%97%B0%EB%A0%B9%EB%8C%80%20%EB%B6%84%ED%8F%AC.svg)\n\n롯데백화점부산본점은 현대백화점부산점에 비해 방문자의 연령대분포가 낮아진 것을 확인할 수 있습니다. 4, 50대 여성의 비율이 다른 쇼핑몰 방문자 평균에 비해 높은 것을 확인할 수 있습니다.\n\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/f90c9f90-2b34-429e-b704-1d1f83cb33ff_%EB%A1%AF%EB%8D%B0%EB%B0%B1%ED%99%94%EC%A0%90%EB%B6%80%EC%82%B0%EB%B3%B8%EC%A0%90%28146130%29%20%EC%97%B0%EB%A0%B9%EB%8C%80%20%EB%B6%84%ED%8F%AC.svg)\n\n신세계백화점센텀시티점은 현대백화점, 롯데백화점보다 방문자의 연령이 어린 것을 확인할 수 있습니다. 특히 2~40대 여성의 비율이 높게 나타납니다.\n\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/cf57e050-06d5-474b-9fcd-3b9490662ba3_%EC%8B%A0%EC%84%B8%EA%B3%84%EB%B0%B1%ED%99%94%EC%A0%90%EC%84%BC%ED%85%80%EC%8B%9C%ED%8B%B0%EC%A0%90%281505596%29%20%EC%97%B0%EB%A0%B9%EB%8C%80%20%EB%B6%84%ED%8F%AC.svg)\n\n",
    },
    {
      id: "21",
      category: "인사이트",
      isNew: true,
      cardType: "normal",
      dataType: "insights",
      type: "report",
      imgSrc: `/images/puzzle_card_poi2.png`,
      title: "10,20대와 30,40대가 방문하는 쇼핑몰",
      displayName: "10,20대와 30,40대가 방문하는 쇼핑몰",
      partner: "SKTelecom",
      tagList: ["여가", "쇼핑", "장소"],
      description:
        "2022년 2월 기준 방문자들의 연령대/성별 분포를 통해 장소별 방문자의 특징을 확인해보세요. 그래프의 색깔은 스타필드하남에 방문한 해당 연령대/성별의 비율이 원래 그 연령대/성별의 비율보다 높다는 것을 의미합니다. 스타필드하남과 스타필드안성의 경우 3,40대 남성과 여성 비율이 높게 나타나는 것을 알 수 있습니다. 더현대서울과 롯데백화점에비뉴엘월드타워점, 신세계백화점천안아산점은 10, 20대의 비율이 스타필드에 비해 상당히 높은 것을 확인할 수 있습니다.",
      reportContent:
        "\n2022년 2월 기준 방문자들의 연령대/성별 분포를 통해 장소별 방문자의 특징을 확인해보세요. 그래프의 색깔은 스타필드하남에 방문한 해당 연령대/성별의 비율이 원래 그 연령대/성별의 비율보다 높다는 것을 의미합니다.\n\n스타필드하남과 스타필드안성의 경우 3,40대 남성과 여성 비율이 높게 나타나는 것을 알 수 있습니다.\n\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/708a3545-5d2d-4c4e-b834-742de927cfc5_%EC%8A%A4%ED%83%80%ED%95%84%EB%93%9C%ED%95%98%EB%82%A8%285411247%29%20%EC%97%B0%EB%A0%B9%EB%8C%80%20%EB%B6%84%ED%8F%AC.svg)\n\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/d898bafb-012e-451d-bcd1-b857f9554cd0_%EC%8A%A4%ED%83%80%ED%95%84%EB%93%9C%EC%95%88%EC%84%B1%288875892%29%20%EC%97%B0%EB%A0%B9%EB%8C%80%20%EB%B6%84%ED%8F%AC.svg)\n\n더현대서울과 롯데백화점에비뉴엘월드타워점, 신세계백화점천안아산점은 10, 20대의 비율이 스타필드에 비해 상당히 높은 것을 확인할 수 있습니다.\n\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/1fe20a45-d94d-4f0c-9f8f-c7cbb111b5a8_%EB%8D%94%ED%98%84%EB%8C%80%EC%84%9C%EC%9A%B8%2810067845%29%20%EC%97%B0%EB%A0%B9%EB%8C%80%20%EB%B6%84%ED%8F%AC.svg)\n\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/2afc811f-2c36-49a1-8056-9089f4629621_%EB%A1%AF%EB%8D%B0%EB%B0%B1%ED%99%94%EC%A0%90%EC%97%90%EB%B9%84%EB%89%B4%EC%97%98%EC%9B%94%EB%93%9C%ED%83%80%EC%9B%8C%EC%A0%90%285783805%29%20%EC%97%B0%EB%A0%B9%EB%8C%80%20%EB%B6%84%ED%8F%AC.svg)\n\n![900,605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/f2890fdb-bf75-4d07-82e7-f73d48f2b100_%EC%8B%A0%EC%84%B8%EA%B3%84%EB%B0%B1%ED%99%94%EC%A0%90%EC%B2%9C%EC%95%88%EC%95%84%EC%82%B0%EC%A0%90%282362143%29%20%EC%97%B0%EB%A0%B9%EB%8C%80%20%EB%B6%84%ED%8F%AC.svg)\n\n",
    },
    {
      id: "22",
      category: "인사이트",
      isNew: true,
      cardType: "normal",
      dataType: "insights",
      type: "report",
      imgSrc: `/images/puzzle_card_poi3.png`,
      title: "설날(구정) 당일 면적 당 방문 고객이 많은 백화점 순위",
      displayName: "설날(구정) 당일 면적 당 방문 고객이 많은 백화점 순위",
      partner: "SKTelecom",
      tagList: ["여가", "쇼핑", "장소"],
      description:
        "POI별로 면적 당 방문인원 수를 비교할 수 있습니다. 구정 당일(2022.02.01) 점심과 저녁 시간, 면적 당 방문인원이 많았던 백화점 TOP10을 확인해보세요",
      reportContent:
        "\nPOI별로 면적 당 방문 인원 수를 비교할 수 있습니다. 구정 당일(2022.02.01) 점심과 저녁 시간, 면적 당 방문 인원이 많았던 상위 10개의 백화점을 확인해보세요.\n\n![900, 605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/2856637d-541f-4ef8-8f6a-644fd430bc08_fig.svg)\n\n",
    },
    {
      id: "23",
      category: "인사이트",
      isNew: true,
      cardType: "normal",
      dataType: "insights",
      type: "report",
      imgSrc: `/images/puzzle_card_poi4.png`,
      title: "스타필드 고양,안성, 하남의 면적 당 방문 인원 비교",
      displayName: "스타필드 고양,안성, 하남의 면적 당 방문 인원 비교",
      partner: "SKTelecom",
      tagList: ["여가", "쇼핑", "장소"],
      description:
        "백화점, 쇼핑몰별로 면적 당 방문인원 수를 비교할 수 있습니다. 구정 당일(2022.02.01) 시간대별로 스타필드고양, 스타필드안성, 스타필드하남의 절대혼잡도를 확인해보세요. y축의 수치는 1m²당 인원 수를 의미하며, 해당 수치가 클수록 면적 당 방문인원이 많다는 의미를 가지고 있습니다. 차트를 통하여 스타필드하남이 다른 두 지점에 비하여 면적 당 방문인원이 많다는 것을 알 수 있습니다",
      reportContent:
        "\n백화점, 쇼핑몰별로 면적 당 방문 인원 수를 비교할 수 있습니다. 구정 당일(2022.02.01) 시간대별로 스타필드고양, 스타필드안성, 스타필드하남의 절대혼잡도를 확인해보세요. y축의 수치는 1m²당 인원 수를 의미하며, 해당 수치가 클수록 면적 당 방문 인원이 많음을 뜻합니다.\n\n차트를 통하여 스타필드하남이 다른 두 지점에 비하여 면적 당 방문 인원이 많았음을 알 수 있습니다.\n\n![900, 605.84](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/29c3ad57-4edd-4605-9247-2e17faf01d1c_fig.svg)\n\n",
    },
  ],
  "국내-여행": [
    {
      id: "1",
      imgSrc: `/images/puzzle_card_travel1.png`,
      title: "여행지별 인기 방문 지역 및 체류 시간",
      category: "체험형 인사이트",
      isNew: false,
      description:
        "이번주에는 가족끼리 어디로 여행을 갈까? 인기 여행지를 알아보세요.",
      tagList: ["여행", "라이프스타일"],
      cardType: "normal",
      dataType: "insights",
      type: "interactive",
      interactiveType: "travelPopularEmdRi",
      reportContent: null,
      displayName: "인기-여행지",
    },
    {
      id: "2",
      imgSrc: `/images/puzzle_card_travel2.png`,
      title: "여행자 수 트렌드",
      category: "체험형 인사이트",
      isNew: false,
      description:
        "관심있는 여행지의 최근 2주간 여행자 수 트렌드를 알아보세요.",
      tagList: ["여행", "라이프스타일"],
      cardType: "normal",
      dataType: "insights",
      type: "interactive",
      interactiveType: "travelTravelerDaily",
      reportContent: null,
      displayName: "여행자수-트렌드",
    },
    {
      id: "3",
      imgSrc: `/images/puzzle_card_travel3.png`,
      title: "시도에 따른 1박2일 여행지 비교",
      category: "인사이트",
      isNew: false,
      description:
        "서울 출발 vs 경상남도 출발 1박2일 인기 여행지 Top 10 입니다.",
      tagList: ["여행", "라이프스타일"],
      cardType: "normal",
      dataType: "insights",
      type: "report",
      interactiveType: null,
      reportContent:
        "\n\n# 1박2일 여행지\n## 시도에 따른 1박2일 여행지 비교 \n\n서울 출발 vs 경상남도 출발 1박2일 인기 여행지 Top 10 입니다. \n\n![Image](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/a6da51af-6c4e-497a-9634-75b8135d1bbe_fig.svg)\n\n\n\n##### [자료 기준]\n##### - 데이터 기간 : 2021.11.01. ~ 2021.11.20.     \n##### - ranking 기준 : 여행자수     \n",
      displayName: "시도에-따른-1박2일-여행지-비교",
    },
    {
      id: "3",
      imgSrc: `/images/puzzle_card_travel4.png`,
      title: "아이와 함께 갈만한 여행장소",
      category: "인사이트",
      isNew: false,
      description:
        "제주도 제주시에서 아이와 여행할 때 특히 많이 방문하는 장소 Top10 입니다.",
      tagList: ["여행", "라이프스타일", "육아"],
      cardType: "normal",
      dataType: "insights",
      type: "report",
      interactiveType: null,
      reportContent:
        "\n\n# 아이와 함께 갈만한 여행장소\n## 제주도 제주시편 \n\n제주도 제주시에서 아이와 여행할 때 특히 많이 방문하는 장소 Top10 입니다.\n\n![Image](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/27dcad80-030e-49f4-b43b-49abd221e1e2_fig.svg)\n\n\n\n##### [자료 기준]\n##### - 데이터 기간 : 2021.12.16. ~ 2022.01.16.     \n##### - 지역기준 : 제주도 제주시       \n##### - 장소선정 기준 : 방문자 비율과 방문 lift 기준을 조합하여 장소 선정     \n\n\n",
      displayName: "아이와-함께-갈만한-여행장소",
    },
  ],
  주거생활: [
    {
      id: "2",
      imgSrc: `/images/puzzle_card_apt1.png`,
      title: "유사 아파트",
      category: "체험형 인사이트",
      isNew: false,
      description:
        "검색한 아파트와 유사한 라이프스타일을 가지고 있는 다른 아파트들을 알아보세요.",
      tagList: ["주거", "라이프스타일"],
      cardType: "normal",
      dataType: "insights",
      type: "interactive",
      interactiveType: "aptSimilar",
      reportContent: null,
      displayName: "유사-아파트",
    },
    {
      id: "1",
      imgSrc: `/images/puzzle_card_apt2.png`,
      title: "영유아 상위 비율 아파트",
      category: "인사이트",
      isNew: false,
      description: "영유아 비율이 상대적으로 높은 아파트 상위 10개입니다.",
      tagList: ["아파트", "라이프스타일", "이사", "주거"],
      cardType: "normal",
      dataType: "insights",
      type: "report",
      interactiveType: null,
      reportContent:
        "\n영유아 비율이 상대적으로 높은 아파트 상위 10개입니다.\n\n### 차트 제목 테스트1: 영유아 비율이 상대적으로 높은 아파트 Top 10\n![fig1](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/2b4cbe12-3533-442c-b19c-21f2d0b74578_fig.svg)\n\n### 차트 제목 테스트2: 영유아 비율이 상대적으로 높은 아파트 Top 10\n![gif2](https://hidden-puzzle-hub-file-bucket.s3.ap-northeast-2.amazonaws.com/095d33cb-1b18-4347-a65d-71b275684514_fig.svg)\n\n##### 자료기준\n##### - 2021.12월 기준\n##### - 영유아: SKT회선 기준 유치원/유아교육 통화 이력이 있는 회선...?\n",
      displayName: "영유아-상위-비율-아파트",
    },
  ],
  "공유킥보드-이용": [
    {
      id: "1",
      imgSrc: `/images/puzzle_card_kickboard1.png`,
      title: "공유 킥보드 주 운행 위치",
      category: "체험형 인사이트",
      isNew: false,
      description: "평일/주말별로 공유킥보드의 주요 운행 위치를 확인해보세요.",
      tagList: ["이동", "라이프스타일", "마이크로모빌리티"],
      cardType: "normal",
      dataType: "insights",
      type: "interactive",
      interactiveType: "kickboardHourlyHeat",
      reportContent: null,
      displayName: "공유킥보드-주-운행위치",
    },
    {
      id: "2",
      imgSrc: `/images/puzzle_card_kickboard2.png`,
      title: "공유킥보드 주요 승하차 장소",
      category: "체험형 인사이트",
      isNew: false,
      description: "공유킥보드를 가장 많이 타고, 내리는 위치를 확인해보세요.",
      tagList: ["이동", "라이프스타일", "마이크로모빌리티"],
      cardType: "normal",
      dataType: "insights",
      type: "interactive",
      interactiveType: "kickboardStartEndSpot",
      reportContent: null,
      displayName: "공유킥보드-주요-승하차장소",
    },
  ],
};

export const interactiveDescText: { [key: string]: InteractiveText } = {
  subwayCongestionTrain: {
    desc: `검색한 역으로 진입하는 지하철의 혼잡도를 시간대별로 확인할 수 있습니다.\n(일부 역사의 경우, 검색이 제한될 수 있습니다.)`,
    placeholder: `역사명을 입력해주세요.`,
    footnoteHref: `/data/지하철-혼잡도?tabIndex=1`,
    defaultOption: { title: "강남" },
  },
  subwayCongestionRoute: {
    desc: `검색한 역사 기준으로 사람들이 많이 이용하는 경로의 혼잡도를 제공합니다.\n(도착역은 임의로 설정되며, 일부 역사는 검색이 제한될 수 있습니다.)`,
    placeholder: `출발 역사를 입력해주세요.`,
    footnoteHref: `/data/지하철-혼잡도?tabIndex=1`,
    defaultOption: { title: "인덕원" },
  },
  subwayCongestionCar: {
    desc: `검색한 역으로 진입하는 지하철의 칸별 혼잡도를 확인할 수 있습니다.\n시간대별로 다른 혼잡도 정보와 최다 하차 칸을 확인해 보세요.\n(일부 역사의 경우, 검색이 제한될 수 있습니다.)`,
    placeholder: `역사명을 입력해주세요.`,
    footnoteHref: `/data/지하철-혼잡도?tabIndex=1`,
    defaultOption: { title: "을지로입구" },
  },

  poiCongestionHourly: {
    desc: `장소별로 가장 혼잡한 요일과 시간대가 언제인지 확인해 보세요.\n통계성 장소 혼잡도는 검색한 장소가 요일별, 시간대별로 얼마나 혼잡한지 보여드립니다.\n혼잡도는 과거 1개월 간 가장 혼잡했던 때를 기준으로(100), 요일/시간대별 평균 혼잡도를 상대적으로 표현한 값입니다.\n아래 차트에서 요일을 바꿔가며 혼잡도를 확인해보세요.`,
    placeholder: `장소명을 입력해주세요.`,
    footnoteHref: `/data/장소-혼잡도?tabIndex=1`,
    defaultOption: { title: "스타필드하남", poiId: "5411247" },
  },

  /**
  travelPopularEmdRi: {
    desc: `입력한 여행지 내에서 여행자수 기준 많이 방문하는 지역(동/리) Top5와 평균 방문 시간을 알 수 있습니다.`,
    placeholder: `(시군구단위) 여행지를 입력해주세요.`,
  },

  travelTravelerDaily: {
    desc: `검색한 여행지의 최근 2주간 일별 여행자 수와 총 국내 여행자 수 트렌드를 비교하여 볼 수 있습니다.\n(여행지는 시군구 단위로 검색이 가능합니다.)`,
    placeholder: `(시군구단위) 여행지를 입력해주세요.`,
  },

  aptSimilar: {
    desc: `검색한 아파트와 거주자 특징, 라이프스타일이 비슷한 상위 5개 아파트를 보여드립니다.\n지도 위에 표시된 아파트 목록과 아파트별 특징이 담긴 태그도 함께 확인해보세요.\n(모수 불충분 등으로 집계가 불가능한 일부 아파트의 경우 검색이 제한될 수 있습니다.)`,
    placeholder: `아파트를 입력해주세요.`,
  },

  kickboardHourlyHeat: {
    desc: `검색한 지역구에서 공유 킥보드로 많이 이동한 위치를 보여드립니다.\n평일과 주말 각각 이용자들이 어디서 운행을 많이 하는지 확인해보세요.\n(공유 킥보드 운행 건이 충분히 확보되지 못한 지역구는 검색이 제한될 수 있습니다.)`,
    placeholder: `지역구 명을 입력해주세요.`,
  },

  kickboardStartEndSpot: {
    desc: `검색한 지역구에서 공유 킥보드 이용자들이 가장 많이 승차 또는 하차하는 장소를 보여드립니다.\n(공유 킥보드 운행 건이 충분히 확보되지 못한 지역구는 검색이 제한될 수 있습니다.)`,
    placeholder: `지역구 명을 입력해주세요.`,
  },
  */
};
